#! /usr/bin/env python3

#Statement: 

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

top = 4000000
sum = 0

def fibi(high,low):
	fib = [high+low,high]
	return fib

first = 1
second = 2
fib = fibi(second,first)
print(fib)
while fib[0]<top:
	fib = fibi(fib[0],fib[1])
#	print(fib)
	if fib[0]%2 == 0:
		sum = sum+fib[0]

print(sum+2)
